#!/usr/bin/env bash


# Use dmenu to first select a unity project, then a scene


# unity-projects-dir=$COSDIR

unity_projects_dir="/home/benj/unity-playground/"

cd "$unity_projects_dir"

project=$(fdfind -td -d2 --full-path "/Assets" | cut -d"/" -f1 | dmenu -p "project to open scene in:")

echo selected project: "$project"
# scenes=
