#!/usr/bin/env bash

# The first argument is the name of the unity project you want to operate on.
# The second argument is the method we want to invoke.
# The rest args are optional arguments.

bunel_handle_dir="/tmp/bunel-handles"

[ "$#" -eq 0 ] && echo provide at least the project name as argument && exit 1

mkdir -p $bunel_handle_dir
printf "%s\\n" "${@:2}" > "${bunel_handle_dir}/${1}"
