#!/usr/bin/env bash

assetsMounted=$(mount -l | grep IdleGameSymbolicLink)

SymlinkDir=$COSDIR/IdleGameSymbolicLink

[ -z "$assetsMounted" ] && sudo mkdir -p $SymlinkDir/Assets && sudo mount --bind $IDLEGAMEDIR/Assets $SymlinkDir/Assets

unityArgs="-forcefree -CacheServerIPAddress 192.168.2.113:80 -buildTarget standalone -projectPath $SymlinkDir"

unity-editor $unityArgs
