#!/bin/sh

touch $HOME/.dbus/Xdbus
chmod 600 $HOME/.dbus/Xdbus
env | grep DBUS_SESSION_BUS_ADDRESS > $HOME/.dbus/Xdbus
echo 'export DBUS_SESSION_BUS_ADDRESS' >> $HOME/.dbus/Xdbus

exit 0



###
# not yet, I have found dotbare util that is trying to manage dotfiles
# with fzf without symlinks somehow. I wanna try that if it works
# and then setup good dotfiles workflow.
# This I've just run once so far but people say it should run every time
#     user logs in:
# uploaded this Shell: bin/dbus-var.sh open in browser
# then you do crontab -e and put something like 15 * * * *
#     /home/nikita/bin/notify.sh (this will run every 15 minutes)

# image Ben
# cool. I'm happy to share best messages as well btw
# ```

# image Nikita Klimenko edited_at: 2020-07-31 17:32:59
# /bin/notify.sh:
# #!/bin/bash

# if [ -r "$HOME/.dbus/Xdbus" ]; then . "$HOME/.dbus/Xdbus"
# fi

# notify-send 'Notifictions' 'Put your notifications here'
#     --icon=dialog-information
